### ISSUE TITLE
如果没有GPU，应该修改哪些呢

### ISSUE THREAD

**Issue by Judy19811** [xieyuankun/Codecfake#6]
使用CPU去运行，出现以下错误，不知道是不是因为CPU的问题呢，
Traceback (most recent call last):
  File "generate_score.py", line 126, in <module>
    generate_score(args.task, model_path)
  File "generate_score.py", line 75, in generate_score
    feats, w2v2_outputs = ADD_model(w2v2)
  File "/home/judy1/projects/AudioForgeryDetection-master/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/judy1/projects/AudioForgeryDetection-master/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/judy1/projects/Codecfake-main/model.py", line 650, in forward
    feat = self.out(feat)
  File "/home/judy1/projects/AudioForgeryDetection-master/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/judy1/projects/AudioForgeryDetection-master/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/judy1/projects/AudioForgeryDetection-master/venv/lib/python3.8/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/judy1/projects/AudioForgeryDetection-master/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/judy1/projects/AudioForgeryDetection-master/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/judy1/projects/AudioForgeryDetection-master/venv/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x24576 and 4960x160)

**Comment by Judy19811** [comment]
已解决
